language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x

script:
  - bundle exec rake test
